name = towny
description = This modpack is a WIP. Towny modpack for Luanti. A township system for Luanti servers. Towny adds claimblocks, towns, residents, and more! It has a unique fixed grid protection system, with mayors owning whole towns and their residents owning plots in their town.
release = 33244
title = Towny
author = livphi
