name = hashimon_wolkers
description = Wolkers — la población nativa de los towns. Cuerpo, FSM local y consejo del servidor madre.
depends = hashimon_core
optional_depends = towny, hashimon_towny, tnt
